apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: db
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0

  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 's11p31b202!';
    FLUSH PRIVILEGES;

