# Primary Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
  namespace: db
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-primary
