apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: dev
data:
  index.html: |
    <html>
    <head><title>Welcome to Nginx!</title></head>
    <body>
    <h1>Hello from Nginx!</h1>
    <p>This is a simple frontend service running in Kubernetes.</p>
    </body>
    </html>

