version: '3.8'
services:
  user-service:
    image: "parksangcheon/backend-repo-user-service:${COMMIT_HASH:-latest}"
    container_name: user-service-container
    depends_on:
      - config-server
      - discovery-server
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
